spring:
  profiles:
    active: local
---
spring:
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    h2:
      console:
        enabled: true

cloud:
  aws:
    s3:
      bucket: chatting
    region:
      static: ap-northeast-2
    stack:
      auto: false
    credentials:
      instanceProfile: true
---
spring.profiles: real
spring.profiles.include: db
spring:
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
